version: "3.3"

volumes:
  postgres-data:

services:
  chat-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: chat/client
    environment:
      - VITE_API_URL=http://localhost:5006
      - VITE_WS_URL=ws://localhost:5006
    ports:
      - "5008:80"
  chat-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: chat/api
    environment:
      - POSTGRES_CONNECTION_URI=postgres://postgres:password@postgres:5432/chat
    ports:
      - "5006:80"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat
    ports:
      - "5005:5432"
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
